require 'yaml'
require 'fileutils'

fastlane_version "2.48.0"

default_platform :ios

PROJECT_NAME = ENV['PROJECT_NAME']
BUILD_NUMBER = ENV['BUILD_NUMBER']

platform :ios do

  lane :build do

    unlock_keychain(path: "login.keychain", password: ENV["KEYCHAIN_PASSWORD"])
    cocoapods
    match(type: "appstore")

    build_number = ENV["BUILD_NUMBER"].to_i
    increment_build_number(build_number: build_number)

    changelog = YAML.load_file('../../CHANGELOG.yml')
    version_number = changelog['upcoming']['version']
    increment_version_number(version_number: version_number)

    gym(scheme: "#{PROJECT_NAME}", output_directory: "./output", export_method: "app-store")

    commit_version_bump(
      message: "Deploying version #{version_number} (#{build_number})",
      xcodeproj: "./#{PROJECT_NAME}.xcodeproj",
      force: true
    )

    add_git_tag tag: "#{version_number}_#{build_number}"
    push_to_git_remote

  end

  desc "Submit a new Build to TestFlight for Beta testing"
  lane :beta do
    changelog = YAML.load_file('../../CHANGELOG.yml')
    version_number = changelog['upcoming']['version']
    build_number = ENV["BUILD_NUMBER"].to_i
    release_notes = changelog['upcoming']['notes'].map{ |note| note.prepend '- ' }.join("\n")

    pilot(ipa: "./output/#{PROJECT_NAME}.ipa", skip_waiting_for_build_processing: true)

    slack(
			message: "Successfully deployed #{PROJECT_NAME} v#{version_number}_#{build_number} to TestFlight: " + release_notes,
			channel: "shadaloo"
		)
  end

  lane :prod do

    `unzip ../output/#{PROJECT_NAME}.ipa`
    `plutil -convert xml1 Payload/#{PROJECT_NAME}.app/Info.plist`
    if File.readlines("Payload/#{PROJECT_NAME}.app/Info.plist").grep(/staging|dev|localhost/).size > 0
      puts("plist contains text (staging/dev/localhost) that makes us believe you may be trying to release whilst pointing to a non-live endpoint. Program will now exit.")
      return
    end

    changelog = YAML.load_file('../../CHANGELOG.yml')
    version_number = changelog['upcoming']['version']
    build_number = ENV["BUILD_NUMBER"].to_i
    release_notes = changelog['upcoming']['notes'].map{ |note| note.prepend '- ' }.join("\n")

    deliver(ipa: "./output/#{PROJECT_NAME}.ipa")

    slack(
			message: "Successfully deployed #{PROJECT_NAME} v#{version_number}_#{build_number} to the App Store: " + release_notes,
			channel: "shadaloo"
		)
  end

end
